### ISSUE TITLE
Hi, could you please tell me where do you get the input time-dependent link travel time data?

### ISSUE THREAD

**Issue by orietrans** [10heey1/TDSPP#1]
Hi, could you please tell me where do you get the input time-dependent link travel time data?

I'm also curious about the paper mentioned in your README. 

It would be great if you can provide the title of that paper, too.

**Comment by 10heey1** [comment]
Hi Marco, the paper has been accepted but not published yet in IJOC. An earlier version of it is available in http://www.optimization-online.org/DB_FILE/2019/02/7082.pdf

Dynamic Discretization Discovery Algorithms for Time-Dependent Shortest Path Problems

Let me know if you have further questions, I am happy to hop on a brief call and would love to know what you are working on.

**Comment by orietrans** [comment]
Thank you for your kind help!
